// options.js

export const allOptions = [
    "React",
    "React.js",
    "ReactJS",
    "All of the above",
    "React.js can increase the application's performance with Virtual DOM.",
    "React.js is easy to integrate with other frameworks such as Angular, BackboneJS since it is only a view library.",
    "React.js can render both on client and server side.",
    "React.js has only a view layer. We have put your code for Ajax requests, events and so on.",
    "The library of React.js is pretty large.",
    "The JSX in React.js makes code easy to read and write.",
    "The learning curve can be steep in React.js.",
    "npm install -g create-react-app",
    "npx create-react-app my-app",
    "npm install create-react-app",
    "npm install -f create-react-app",
    "Original DOM",
    "Virtual DOM",
    "Both A and B.",
    "None of the above.",
    "3000",
    "8080",
    "3030",
    "6060",
    "1",
    "2",
    "3",
    "Unlimited",
    "Using the reduce array method",
    "Using the <Each /> component",
    "Using the Array.map() method",
    "With a for/while loop",
    "A permanent storage.",
    "Internal storage of the component.",
    "External storage of the component.",
    "None of the above.",
    "State & Props",
    "Services & Components",
    "State & Services",
    "State & Component"
];
